/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.temconverter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author Suraj Senapati
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Convertbutton.addActionListener((ActionEvent e) -> {
            convertTemperature();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JLabel();
        Tempinput = new javax.swing.JTextField();
        inputtemp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Selectunit = new javax.swing.JLabel();
        Units = new javax.swing.JComboBox<>();
        Convertbutton = new javax.swing.JButton();
        Celsiuslabel = new javax.swing.JLabel();
        Fahrenheitlabel = new javax.swing.JLabel();
        Kelvinlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("mainframe"); // NOI18N

        Heading.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        Heading.setText("TEMPERATURE CONVERTER");

        Tempinput.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Tempinput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        inputtemp.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        inputtemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputtemp.setText("Enter Temperature : ");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/temconverter/logo.png"))); // NOI18N

        Selectunit.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Selectunit.setText("Select Unit :");

        Units.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Units.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        Units.setToolTipText("");

        Convertbutton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Convertbutton.setText("Convert");
        Convertbutton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Celsiuslabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Celsiuslabel.setText("Celsius  : ");

        Fahrenheitlabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Fahrenheitlabel.setText("Fahrenheit  : ");

        Kelvinlabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Kelvinlabel.setText("Kelvin  : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Heading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(Convertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Celsiuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Selectunit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputtemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tempinput)
                            .addComponent(Units, 0, 285, Short.MAX_VALUE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fahrenheitlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kelvinlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tempinput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputtemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Selectunit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Units, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(Convertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Celsiuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fahrenheitlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kelvinlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private void convertTemperature() {
        try {
            double inputTemperature = Double.parseDouble(Tempinput.getText());
            String selectedUnit = (String) Units.getSelectedItem();

            double celsius = 0, fahrenheit = 0, kelvin = 0;

            switch (selectedUnit) {
                case "Celsius" -> {
                    celsius = inputTemperature;
                    fahrenheit = celsius * 9 / 5 + 32;
                    kelvin = celsius + 273.15;
                }
                case "Fahrenheit" -> {
                    fahrenheit = inputTemperature;
                    celsius = (fahrenheit - 32) * 5 / 9;
                    kelvin = celsius + 273.15;
                }
                case "Kelvin" -> {
                    kelvin = inputTemperature;
                    celsius = kelvin - 273.15;
                    fahrenheit = celsius * 9 / 5 + 32;
                }
            }

            Celsiuslabel.setText("Celsius: " + String.format("%.2f", celsius));
            Fahrenheitlabel.setText("Fahrenheit: " + String.format("%.2f", fahrenheit));
            Kelvinlabel.setText("Kelvin: " + String.format("%.2f", kelvin));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number.", "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Celsiuslabel;
    private javax.swing.JButton Convertbutton;
    private javax.swing.JLabel Fahrenheitlabel;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Kelvinlabel;
    private javax.swing.JLabel Selectunit;
    private javax.swing.JTextField Tempinput;
    private javax.swing.JComboBox<String> Units;
    private javax.swing.JLabel inputtemp;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
